[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "logical-brutalism"
version = "1.4.0"
description = "Parametric Engine Deployment for Backend Infrastructure."
authors = [
  { name="Matheus Lacerda Ferreira" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.scripts]
logical-brutalism = "cli.lb_init:main"

[tool.setuptools]
packages = ["cli", "cli.commands", "cli.payloads", "core"]

[tool.setuptools.package-data]
core = ["*.css", "*.js", "*.json"]

