#!/usr/bin/env python3
"""
LOGICAL BRUTALISM :: INIT VITE STATIC COMMAND
Deterministic pipeline to scaffold a vanilla Vite project under LB governance.

Pipeline:
  [00] Validate `npm` and `npx` binary on PATH
  [01] Initialize project with `npx create-vite` (vanilla template)
  [02] Install core dependencies (Vite base)
  [03] Install frontend dependencies: tailwindcss, postcss, autoprefixer, htmx.org, alpinejs
  [04] Overwrite structural files (index.html, main.js)
  [05] Overwrite styling config (tailwind.config.js, postcss.config.js, style.css)
  [06] Finalize and print deployment summary

Author: Matheus Lacerda Ferreira
License: MIT
"""

import os
import shutil

from cli.commands._utils import (
    log,
    ok,
    err,
    run,
    write_file,
    guard_existing_dir,
    C_AMBER,
    C_DIM,
    C_VOID,
)

from cli.payloads.vite_payloads import (
    VITE_INDEX_HTML,
    VITE_MAIN_JS,
    VITE_TAILWIND_CONFIG,
    VITE_POSTCSS_CONFIG,
    VITE_STYLE_CSS,
)

def check_npm():
    """Validate `npm` and `npx` binaries exist on PATH."""
    if shutil.which("npm") is None or shutil.which("npx") is None:
        err(
            "'npm' or 'npx' binary not found.\n"
            "  Logical Brutalism CLI requires Node.js/NPM for Vite scaffolding.\n"
            "  Install Node.js before proceeding."
        )

# ---------------------------------------------------------------------------
# MAIN PIPELINE
# ---------------------------------------------------------------------------
def run_pipeline(project_name):
    """Execute the full `init vite-static` deployment pipeline.

    Args:
        project_name: Name of the Vite project directory to create.
    """
    project_dir = os.path.join(os.getcwd(), project_name)

    # Guard: prevent overwriting
    guard_existing_dir(project_dir)

    npx_bin = shutil.which("npx")
    npm_bin = shutil.which("npm")

    # -- Step 00: Validate NPM -----------------------------------------------
    log("00", "Validating npm/npx binaries...")
    check_npm()
    ok("Node package manager detected on PATH.")

    # -- Step 01: Initialize project with Vite -------------------------------
    log("01", f"Initializing vanilla Vite project: {project_name}")
    # Using npx -y to avoid interactive prompts, scaffolding vanilla JS
    run([npx_bin, "-y", "create-vite@latest", project_name, "--template", "vanilla"])
    ok(f"Project directory created :: {project_dir}")

    # -- Step 02: Install base dependencies -----------------------------------
    log("02", "Installing base Vite dependencies")
    run([npm_bin, "install"], cwd=project_dir)
    ok("Base dependencies locked and installed.")

    # -- Step 03: Install LB frontend dependencies ----------------------------
    log("03", "Installing LB frontend stack: tailwindcss (v3), postcss, autoprefixer, htmx.org, alpinejs")
    run(
        [npm_bin, "install", "tailwindcss@^3.4.17", "postcss", "autoprefixer", "htmx.org", "alpinejs"],
        cwd=project_dir,
    )
    ok("Frontend dependencies installed.")

    # -- Step 04: Overwrite structural files ----------------------------------
    log("04", "Injecting structural HTML and JS entry point")
    write_file(os.path.join(project_dir, "index.html"), VITE_INDEX_HTML)
    ok("Root template :: index.html")
    
    write_file(os.path.join(project_dir, "main.js"), VITE_MAIN_JS)
    ok("Application entry :: main.js")

    # -- Step 05: Overwrite styling configs -----------------------------------
    log("05", "Locking Tailwind/PostCSS configuration matrix")
    write_file(os.path.join(project_dir, "tailwind.config.js"), VITE_TAILWIND_CONFIG)
    ok("Tailwind config locked :: tailwind.config.js")

    write_file(os.path.join(project_dir, "postcss.config.js"), VITE_POSTCSS_CONFIG)
    ok("PostCSS config locked :: postcss.config.js")

    write_file(os.path.join(project_dir, "style.css"), VITE_STYLE_CSS)
    ok("Tailwind input directive :: style.css")

    # -- Step 06: Finalize ----------------------------------------------------
    log("06", "Finalizing deployment")

    # Remove counter.js generated by vanilla template if it exists
    counter_js = os.path.join(project_dir, "counter.js")
    if os.path.exists(counter_js):
        os.remove(counter_js)
    
    # Print summary
    print(f"\n {C_AMBER}{'=' * 64}{C_VOID}")
    print(f" {C_AMBER}[DEPLOYMENT COMPLETE]{C_VOID}")
    print(f" {C_AMBER}{'=' * 64}{C_VOID}\n")
    print(f" {C_DIM}Project:{C_VOID}    {project_name}/")
    print(f" {C_DIM}Server:{C_VOID}     cd {project_name} && npm run dev")
    print(f" {C_DIM}Build:{C_VOID}      cd {project_name} && npm run build\n")
    print(f" {C_AMBER}[>]{C_VOID} WHAT DOES NOT RESOLVE, DOES NOT EXIST.\n")
